backend:
  # Use netlify identity as backend
  branch: master
  ### enable below lines for github integration ###
  name: github
  repo: foundations-design/janemilym
media_folder: "site/static/img"
public_folder: "/img"
  
# Please run "npx netlify-cms-proxy-server" for local backend
# Requires Netlify Config at "Site Configuration -> Build & Deploy -> Deploy Notifications"
local_backend: true
publish_mode: editorial_workflow
collections:
  - name: "theme"
    label: "Theme"
    files: 
      - file: "site/_data/theme.yaml"
        name: "Theme"
        label: "Theme"
        fields: 
          - {label: "Sidebar Color", name: "sidebarColor", widget: "color", allowInput: true, hint: "Accepts color in any HTML-friendly format, including [color names (link)](https://www.w3schools.com/tags/ref_colornames.asp)"}
          - {label: "Header Color", name: "headingColor", widget: "color", allowInput: true, hint: "Accepts color in any HTML-friendly format, including [color names (link)](https://www.w3schools.com/tags/ref_colornames.asp)"}
  - name: "content" # Used in routes, e.g., /admin/collections/resume
    label: "Content" # Used in the UI
    # folder: "_resume" # The path to the folder where the documents are stored
    # create: true # Allow users to create new documents in this collection
    files: # The fields for each document, usually in front matter
      - name: "site"
        label: "Site Settings (Name, Title, Profile Picture)"
        file: "site/_data/site.yaml"
        fields: 
          - {label: "Name", name: "name", widget: "string", required: false}
          - {label: "Title", name: "title", widget: "string", required: false}
          - {label: "Profile Picture", name: "pic", widget: "image", required: false}
      - name: "home"
        label: "Home"
        file: "site/_data/index-content.md"
        fields: 
          - widget: "markdown"
            label: "content"
            name: "body"
      - name: "cv"
        label: "Curriculum Vitae"
        file: "site/_data/cv.yaml"
        fields:
          - label: "Institutions"
            widget: "list"
            name: "Education"
            fields:
              - {label: "Degree", name: "Degree", widget: "string"}
              - {label: "Institution", name: "Institution", widget: "string"}
              - {label: "Location", name: "Location", widget: "string"}
              - {label: "Duration (ex. Dec 2018 â€“ Aug 2022)", name: "Duration", widget: "string", default: ""}
              - {label: "GPA", name: "GPA", widget: "string", required: false}
              - {label: "Details", name: "Details", widget: "list", required: false}
          - label: "Work Experiences"
            name: "WorkExperience"
            widget: "list"
            fields:
              - {label: "Position", name: "Position", widget: "string"}
              - {label: "Institution", name: "Institution", widget: "string"}
              - {label: "Location", name: "Location", widget: "string"}
              - {label: "Duration", name: "Duration", widget: "string"}
              - {label: "Responsibilities", name: "Responsibilities", widget: "list"}
          - label: "Leadership Experiences"
            name: "LeadershipExperience"
            widget: "list"
            fields:
              - {label: "Position", name: "Position", widget: "string"}
              - {label: "Institution", name: "Institution", widget: "string"}
              - {label: "Location", name: "Location", widget: "string", required: false}
              - {label: "Duration", name: "Duration", widget: "string"}
              - {label: "Responsibilities", name: "Responsibilities", widget: "list"}
          - label: "Skills"
            name: "Skills"
            widget: "list"
      - name: "social"
        label: "Social Links"
        file: "site/_data/social.yaml"
        fields:
          - label: "Social Links"
            name: "links"
            widget: "list"
            fields:
              - label: "URL"
                name: "url"
                widget: "string"
              - label: "Icon"
                name: "image"
                widget: "image"
                media_library:
                  config:
                    multiple: false
  - name: "project"
    label: "Projects"
    folder: "site/projects"
    create: true
    fields:
      - {label: "Profile Picture", name: "pic", widget: "image", required: false}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "body", widget: "string"}